name: Cypress Tests

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          working-directory: ./tests/e2e
          publish-summary: true

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: ignore
          path: |
            tests/e2e/cypress/videos
            tests/e2e/cypress/screenshots
            tests/e2e/cypress/reports