name: Cypress Tests

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run example tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./tests/e2e

      - name: Saving artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: ignore
          path: |
            tests/e2e/cypress/videos
            tests/e2e/cypress/screenshots
            tests/e2e/cypress/reports